name: $(Build.BuildId)

variables:
- group: Secrets
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'

pool:
  name: WaldoHetzner

steps:
- checkout: self
  clean: true
  
- task: ALOpsDockerStart@1
  inputs:
    docker_image: $(dockerimage)
    docker_pull: true
    # docker_login: 'Insider Docker Registry'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc.license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

# - task: ALOpsAppTest@1
#   inputs:
#     usedocker: true
#     import_action: "Skip"
#     testfilter: $(TestFilter)
#     show_available_tests: true
#   continueOnError: true    

# - task: PublishTestResults@1
#   inputs:
#     testResultsFormat: XUnit
#     testResultsFiles: '**/TestResults.xml'
#     testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()
  # inputs:
    # docker_login: 'Insider Docker Registry'

- task: PublishBuildArtifacts@1
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Base'
    publishLocation: 'Container'